// Copyright 2022. ceres
// Author https://github.com/go-ceres/ceres
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"github.com/go-ceres/ceres/pkg/proto/api"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"net/http"
	"os"
	"regexp"
	"strings"
)

const (
	contextPackage = protogen.GoImportPath("context")
	httpPackage    = protogen.GoImportPath("github.com/go-ceres/ceres/pkg/transport/http")
)

var methodSets = make(map[string]int)

// Generator 定义生成器
type Generator struct {
	gen         *protogen.Plugin
	file        *protogen.File
	writer      *protogen.GeneratedFile
	httpPackage string
	omitempty   bool // 是否忽略掉没有配置路由的方法
}

// Run 开始生成
func (g *Generator) Run() {
	g.P("// Code generated by protoc-gen-ceres. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-ceres %s", Version))
	g.P("// - protoc             ", g.getProtocVersion())
	if g.file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", g.file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", g.file.Desc.Path())
	}
	g.P()
	g.P("package ", g.file.GoPackageName)
	g.P()
	g.genFileContent()
}

// writeFileContent 写出文件内容
func (g *Generator) genFileContent() {
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the ceres package it is being compiled against.")
	g.P("var _ = new(", contextPackage.Ident("Context"), ")")
	g.P("const _ = ", httpPackage.Ident("SupportPackageIsVersion1"))
	g.P()
	str := g.writer.QualifiedGoIdent(protogen.GoIdent{
		GoName:       "ceres-go",
		GoImportPath: httpPackage,
	})
	g.httpPackage = strings.TrimSuffix(str, ".ceres-go")
	g.printf("%s----------------%s", str, strings.TrimSuffix(str, ".ceres-go"))
	for _, service := range g.file.Services {
		g.genService(service)
	}
}

// genService 生成
func (g *Generator) genService(service *protogen.Service) {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	// HTTP Server.
	sd := &serviceDesc{
		HttpPath:    g.httpPackage,
		ServiceType: service.GoName,
		ServiceName: string(service.Desc.FullName()),
		Metadata:    g.file.Desc.Path(),
	}
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			continue
		}
		g.printf("这是获取到的path:%s", proto.GetExtension(method.Desc.Options(), api.E_Get))
		if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Get).(string); ok && path != "" {
			g.printf("获取到了get方法: path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodGet, path))
		} else if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Post).(string); ok && path != "" {
			g.printf("获取到了post方法,path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodPost, path))
		} else if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Put).(string); ok && path != "" {
			g.printf("获取到了post方法,path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodPut, path))
		} else if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Delete).(string); ok && path != "" {
			g.printf("获取到了post方法,path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodDelete, path))
		} else if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Options).(string); ok && path != "" {
			g.printf("获取到了post方法,path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodOptions, path))
		} else if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Patch).(string); ok && path != "" {
			g.printf("获取到了post方法,path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodPatch, path))
		} else if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Head).(string); ok && path != "" {
			g.printf("获取到了post方法,path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodHead, path))
		} else if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Connect).(string); ok && path != "" {
			g.printf("获取到了post方法,path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodConnect, path))
		} else if path, ok := proto.GetExtension(method.Desc.Options(), api.E_Trace).(string); ok && path != "" {
			g.printf("获取到了post方法,path是%s", path)
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodTrace, path))
		} else if !g.omitempty {
			path := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
			sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodPost, path))
		}

		//rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
		//if rule != nil && ok {
		//	for _, bind := range rule.AdditionalBindings {
		//		sd.Methods = append(sd.Methods, g.buildHTTPRule(method, bind))
		//	}
		//	sd.Methods = append(sd.Methods, g.buildHTTPRule(method, rule))
		//} else if !g.omitempty {
		//	path := fmt.Sprintf("/%s/%s", service.Desc.FullName(), method.Desc.Name())
		//	sd.Methods = append(sd.Methods, g.buildMethodDesc(method, http.MethodPost, path))
		//}
	}
	if len(sd.Methods) != 0 {
		g.P(sd.execute())
	}
}

//func (g *Generator) buildHTTPRule(m *protogen.Method, rule *annotations.HttpRule) *methodDesc {
//	var (
//		path         string
//		method       string
//		responseBody string
//	)
//
//	switch pattern := rule.Pattern.(type) {
//	case *annotations.HttpRule_Get:
//		path = pattern.Get
//		method = http.MethodGet
//	case *annotations.HttpRule_Put:
//		path = pattern.Put
//		method = http.MethodPut
//	case *annotations.HttpRule_Post:
//		path = pattern.Post
//		method = http.MethodPost
//	case *annotations.HttpRule_Delete:
//		path = pattern.Delete
//		method = http.MethodDelete
//	case *annotations.HttpRule_Patch:
//		path = pattern.Patch
//		method = http.MethodPatch
//	case *annotations.HttpRule_Custom:
//		path = pattern.Custom.Path
//		method = pattern.Custom.Kind
//	}
//	responseBody = rule.ResponseBody
//	md := g.buildMethodDesc(m, method, path)
//	if responseBody == "*" {
//		md.ResponseBody = ""
//	} else if responseBody != "" {
//		md.ResponseBody = "." + camelCaseVars(responseBody)
//	}
//	return md
//}

func (g *Generator) buildMethodDesc(m *protogen.Method, method, path string) *methodDesc {
	defer func() { methodSets[m.GoName]++ }()

	return &methodDesc{
		Name:         m.GoName,
		OriginalName: string(m.Desc.Name()),
		Num:          methodSets[m.GoName],
		Request:      g.writer.QualifiedGoIdent(m.Input.GoIdent),
		Reply:        g.writer.QualifiedGoIdent(m.Output.GoIdent),
		Path:         path,
		Method:       method,
	}
}

// printf 打印日志
func (g *Generator) printf(msg string, arg ...interface{}) {
	fmt.Fprintf(os.Stderr, msg, arg...)
}

// getProtocVersion 获取protoc版本
func (g *Generator) getProtocVersion() string {
	v := g.gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

// P 写入信息到文件
func (g *Generator) P(v ...interface{}) {
	g.writer.P(v...)
}

// hasHTTPRule 判断是否包含http路由
func hasHTTPRule(file *protogen.File) bool {
	for _, service := range file.Services {
		for _, method := range service.Methods {
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				continue
			}
			if proto.HasExtension(method.Desc.Options(), api.E_Get) {
				return true
			} else if proto.HasExtension(method.Desc.Options(), api.E_Post) {
				return true
			} else if proto.HasExtension(method.Desc.Options(), api.E_Put) {
				return true
			} else if proto.HasExtension(method.Desc.Options(), api.E_Patch) {
				return true
			} else if proto.HasExtension(method.Desc.Options(), api.E_Delete) {
				return true
			} else if proto.HasExtension(method.Desc.Options(), api.E_Options) {
				return true
			} else if proto.HasExtension(method.Desc.Options(), api.E_Head) {
				return true
			} else if proto.HasExtension(method.Desc.Options(), api.E_Connect) {
				return true
			} else if proto.HasExtension(method.Desc.Options(), api.E_Trace) {
				return true
			}
		}
	}
	return false
}

func replacePath(name string, value string, path string) string {
	pattern := regexp.MustCompile(fmt.Sprintf(`(?i){([\s]*%s[\s]*)=?([^{}]*)}`, name))
	idx := pattern.FindStringIndex(path)
	if len(idx) > 0 {
		path = fmt.Sprintf("%s{%s:%s}%s",
			path[:idx[0]], // The start of the match
			name,
			strings.ReplaceAll(value, "*", ".*"),
			path[idx[1]:],
		)
	}
	return path
}

func camelCaseVars(s string) string {
	subs := strings.Split(s, ".")
	vars := make([]string, 0, len(subs))
	for _, sub := range subs {
		vars = append(vars, camelCase(sub))
	}
	return strings.Join(vars, ".")
}

// camelCase returns the CamelCased name.
// If there is an interior underscore followed by a lower case letter,
// drop the underscore and convert the letter to upper case.
// There is a remote possibility of this rewrite causing a name collision,
// but it's so remote we're prepared to pretend it's nonexistent - since the
// C++ generator lowercase names, it's extremely unlikely to have two fields
// with different capitalization.
// In short, _my_field_name_2 becomes XMyFieldName_2.
func camelCase(s string) string {
	if s == "" {
		return ""
	}
	t := make([]byte, 0, 32)
	i := 0
	if s[0] == '_' {
		// Need a capital letter; drop the '_'.
		t = append(t, 'X')
		i++
	}
	// Invariant: if the next letter is lower case, it must be converted
	// to upper case.
	// That is, we process a word at a time, where words are marked by _ or
	// upper case letter. Digits are treated as words.
	for ; i < len(s); i++ {
		c := s[i]
		if c == '_' && i+1 < len(s) && isASCIILower(s[i+1]) {
			continue // Skip the underscore in s.
		}
		if isASCIIDigit(c) {
			t = append(t, c)
			continue
		}
		// Assume we have a letter now - if not, it's a bogus identifier.
		// The next word is a sequence of characters that must start upper case.
		if isASCIILower(c) {
			c ^= ' ' // Make it a capital letter.
		}
		t = append(t, c) // Guaranteed not lower case.
		// Accept lower case sequence that follows.
		for i+1 < len(s) && isASCIILower(s[i+1]) {
			i++
			t = append(t, s[i])
		}
	}
	return string(t)
}

// Is c an ASCII lower-case letter?
func isASCIILower(c byte) bool {
	return 'a' <= c && c <= 'z'
}

// Is c an ASCII digit?
func isASCIIDigit(c byte) bool {
	return '0' <= c && c <= '9'
}

const deprecationComment = "// Deprecated: Do not use."
